sudo: required

notifications:
  email: 
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change
    on_failure: always
    on_start: never

# Cache:  In $HOME/.ccache; inserts /usr/lib/ccache into $PATH
# https://docs.travis-ci.com/user/caching/#ccache-cache
language: c
cache: ccache

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y lftp
  # - sudo apt-get install -qq sshpass
  # - gem install package_cloud
  # - .travis/check_sftp.sh
  - docker pull "${DOCKER_CONTAINER:-zultron/mk-builder-3}"

env:
  global:
    - JOBS=2
    - DOCKER_CONTAINER=${DOCKER_CONTAINER:-zultron/mk-builder-3}
  matrix:
    # - TAG=jessie-64    CMD=run_tests
    - TAG=jessie-64    CMD=build_deb
    - TAG=jessie-32    CMD=build_deb
    - TAG=jessie-armhf CMD=build_deb
    # - TAG=raspbian-armhf CMD=build_deb

script:
  # - .travis/docker_run.sh
  - .travis/mk-builder-3_deb.sh

after_success:
  # - .travis/send_binaries.sh
  # - test ${TAG} != "raspbian-armhf" && .travis/upload_packagecloud.sh
  #
  # This is broken
  #- .travis/upload_pr_pkgs.sh

after_failure:
  - .travis/upload_failure.sh

# after_script:
#   - .travis/send_status.sh
