sudo: required

notifications:
  email: 
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change
    on_failure: always
    on_start: never

# Cache:  In $HOME/.ccache; inserts /usr/lib/ccache into $PATH
# https://docs.travis-ci.com/user/caching/#ccache-cache
language: c
cache: ccache

services:
  - docker

env:
  global:
    - JOBS=2
    - DOCKER_CONTAINER=${DOCKER_CONTAINER:-zultron/mk-cross-builder}
  matrix:
    - TAG=amd64    CMD=test
    - TAG=amd64    CMD=deb
    - TAG=i386     CMD=deb
    - TAG=armhf    CMD=deb
    - TAG=raspbian CMD=deb

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y lftp
  # - sudo apt-get install -qq sshpass
  # - gem install package_cloud
  # - .travis/check_sftp.sh
  - docker pull "${DOCKER_CONTAINER}:${TAG}"
  # Clear ccache stats
  - ccache -z

script:
  - .travis/docker_build.sh

after_success:
  # - .travis/send_binaries.sh
  # - test ${TAG} != "raspbian-armhf" && .travis/upload_packagecloud.sh
  #
  # This is broken
  #- .travis/upload_pr_pkgs.sh
  # Show ccache stats
  - ccache -s

after_failure:
  - .travis/upload_failure.sh

# after_script:
#   - .travis/send_status.sh
