sudo: required

notifications:
  email: 
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change
    on_failure: always
    on_start: never

# Cache:  In $HOME/.ccache; inserts /usr/lib/ccache into $PATH
# https://docs.travis-ci.com/user/caching/#ccache-cache
language: c
cache: ccache

services:
  - docker

env:
  global:
    - JOBS=2
    - IMAGE=${IMAGE:-dovetailautomata/mk-cross-builder}
  matrix:
    - TAG=amd64    CMD=test
    - TAG=amd64    CMD=deb
    - TAG=i386     CMD=deb
    - TAG=armhf    CMD=deb
    - TAG=raspbian CMD=deb

addons:
  apt:
    packages:
    - lftp
    - sshpass

before_install:
  # Pull the Docker build image
  - docker pull "${IMAGE}:${TAG}"
  # Clear ccache stats
  - ccache -z
  # Install the packagecloud gem for pushing packages
  - gem install package_cloud

script:
  - scripts/build_docker -i $IMAGE -t $TAG -c $CMD

after_success:
  # Upload packages to packagecloud.io
  - scripts/build_upload_packagecloud
  # Show ccache stats
  - ccache -s
